sudo: false
dist: trusty
language: node_js
node_js:
- 8.11.1
cache:
  directories:
  - node_modules
branches:
  only:
  - ft-auth-users-can-see-their-order-history-156826449
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn install
script:
- yarn run test-single
env:
  - PORT=8000
  secure: RL5/gRCW0LMuKIF0cwoR8/QbbN//vOJ8H2SWIRnoKtfs/Am6CW06NZYU1pGD2wymZatY8qcSgM1VNcrVjVU8AN+UjNwtU4cG7K/n8GEN9mAQkam0Sm7mdSrotxk3FtQ18ZM8S1QUDPASgpnMsHyclao9wHRfV1lcw9aF3X5KXQVCm6MS2g58GmpkyOlpcaxAENUmt9QZmzfgVGLiTFddLEO6ail3JR2t33oQ3B4mzMAkvmRDgHVeXTOaTtuvAqNVw/gU2eXSuwaWapz3jCrwmUBbT6Qf9pbVvfIawhSX9H3sFJe64ysKJTI9sHh8hEwSx8g3Jne/3AENo/fdevnZ1UKNinzpifeDNyKICf8oxqvE8kOKsfB4Wjv/9HuAfMOEpxpUW0amXJZ14w+qMhHfe5FtNub1bqebpjaareobBfUpKNuh2PRjTDMUzMYIiuLGT1Ln8WY1H8t0YyvN5e2hbdYbAm1gJv9zFjhgDRLCUCrqOab0WlzzK25OtpDS95ffN5iALgjL1KCF3TOhqUL7EcfOtB0W+FuLj9I75geJgZ0L7WGP0Zgj6oS7aSkr28Clcg24gaUBuLAR9jDJhGMsHJOgA1LsZWKCY8uFVTTzj9IgAvDha3Oa2rD84QMTAmwlUbRBlHhtCw27Vw9pPRzmKEIuWpq7kq9AwPIJDTlpeWU=
