sudo: false
dist: trusty
language: node_js
node_js:
- 8.11.3
services:
- postgresql
cache:
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn install
- psql -c 'create database travis_ci_test;' -U postgres
script:
- yarn test
after_success: yarn coverage
deploy:
  provider: heroku
  api_key:
    secure: ObfAsJRwF2gFZLNRe91z4tFCeWyODRxtvBbOT/4CMv4U7cqAq1wNPDvyG4noR3UASie6rcTTg3uXZ41R1/aulurLBgCB3dGTupOPrUo8xZIZJHwPfGpuyVXM2lHj2P50ZRkEhjGjGmTduaAajqs+ZGICMc12e67StSNfM5EyOGAsUz3WFxW3njXO9oIfb5mSUoJFXkRPPWq7em9+ufJxlRTd6u3Xr64ff8lOsB3oo98yp82gr0EY+jbSLcdATTXbHb/ObT9vaBgQq/30SdFV1vwAdWwxYFNM1Vvhtm89sdg6BR52gtktWO8AE4XfhU1lle9Y+55ENjsbtX70G6BkgwwrW9QNK1tBqlEOH6974XPX8LsPes/jtdkr3+nNBIMRhe7Q+/jf0JJOGcmQP0hIbFqaDs5M/cmf/IJ6vzmgb8AmcRx4HIV/wzLux2CYSJ+Kdjx9cKPEpFJwLYhc6VRFm8bcFnmhs3RNDuffdx2giKNvXOX8iYKCxKzIjTGhHec7SydatJApKDVv4Hk5Xk9xWBrp+4rn8jiAea8O0BqH66qqH1uQumA10RtHmwtmvLW58uvZFDR23uFYnlzPrTWKimQpPaAlk5Kb9URMLLMhFsZQXTie0Phuyq5EIbgEd5tkYuZw2qhtexcXuVoP7HeObdPL1nOiOWb9om3peyg76EA=
  app: dikaeinstein-book-a-meal
  on:
    repo: Dikaeinstein/book-a-meal
    branch: develop
