sudo: false
dist: trusty
language: node_js
node_js:
- 8.11.1
cache:
  directories:
  - node_modules
branches:
  only:
  - ch-integrate-test-coverage-reporting-157145129
  - ch-add-travis-157141554
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn install
script:
- yarn test-single
after_success: yarn coverage
