sudo: false
dist: trusty
language: node_js
node_js:
- 8.11.1
services:
- postgresql
cache:
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn install
- psql -c 'create database travis;' -U postgres
script:
- yarn test-single
after_success: yarn coverage
deploy:
  provider: heroku
  api_key:
    secure: Mo/vl1ERTxdtlLQNXDERRHI7ykVVL2hJf6nLQtbeK2iN7YtiZeiWyCU4c9E9iT+st47Eri11FjNUo4WpQi8vZyv0M+KTa6bxNKXvNwDAdS1DhIBD+z7DFJ0cTHpy9uLDGlzBqC4ciTghCeDAkSLxBdACauM5+uojdu52KFpgpEoBY0E+85gaUXrVPCre295a+ppBiwbxiLyWMkWDA+bCnhOH0mlQKl442T+0dPlbhdJN9OpJSY96gxqsL7+H2xd/bhArhPSyP54fuKxFciUEpivNa42kSqWwFJ/3F8PZGkXT2ntZ2L+DiLo4Yxuw5N5X58dun+2qNzEqTicrfPLaAfrKrdOtDYbB9iTXwCquZoHe81IXHifSEIP7mMR1TGStGrc98Aoq76VpHCPhlbd3m9YUufkB4ja77cW2E6KyFfWy7FCnFh6Z1DMsnbsQxyEcg1ls1Eo6VKb+Mnrjh1xD9Ud5fSdXFTZHpgelEX8Fs3FVujLsnX5/Kr1dGcoRcbmhduMNIjqCLx+vMTcY5mu7RNtpUjUtmQzmAgBemopZBZslUakyTzg4aQQXnxnLFRXE0SzwYrdhRLcZAUyIrRY1vWZ0Nm3UZeeY9x8UDazFLOCsJ3z4KxUrYaufAet0KKNBl6/gI8j+ppDJ3krnwXyPX1F2LvkgzvAVU2+Eha5hnhs=
  app: dikaeinstein-book-a-meal
  on:
    repo: Dikaeinstein/book-a-meal
    branch: ch-move-images-to-cloudinary-157336654
