sudo: false
dist: trusty
language: node_js
node_js: 
  - 8.11.1
cache:
  directories:
    - node_modules
branches:
  only:
    - ft-auth-users-can-see-their-order-history-156826449
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - npm install
script:
  - npm run test
