sudo: false
dist: trusty
language: node_js
node_js:
- 8.11.3
services:
- postgresql
cache:
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn install
- psql -c 'create database book_a_meal_ci_test;' -U postgres
script:
- yarn test
after_success: yarn coverage
deploy:
  provider: heroku
  api_key:
    secure: VkK65N3uMvLfCT/ogHcSoPyYk/iynFVABFHntGAN1QF2AKA7XhLLpQ7kO+sdU4OuSx/f+LiG2B7QUpLfDL8E11raLOJgWPRgvfWUAL+lG3c1/iukr9SKE3W24sIzLf2tcut9oofsRKyGWlRs0H3Z+VmUMWvmph5J4HFRPusrPDuWCFhB2Y6gEzioaq70/MQlFQ1iygDMggNQzeJSUPioYbC4JRTex/feRXTeHRba/qbB68F1b5s+V6x+EhJPF4ZzAUt1a1GRdGrzbjvHKcAY8+SvwqM0FGlnm0wMjxdI2G+NoQ2JFEfwjpfLfy+CdnI51A3/23U5Pj4hYq7o1tX6fspxo5nCQzDrVFlUMTiKXO70aTbnan5DDZOULVHAshHvJoGpU3FUzsHSKJtDFbkgAkdObsg2qxUvGzdnxxJBpcg9tvMiM8wSUWvcQZl8yv1vSEagp3HM9n/lLPCZPnf4Gq/ZlXePCjjMZ+xJXhiKwDBwlP4s3ziwmy0+baV4w29Jjm/EkXsBjV8mPYj1qmgaN94kqiUWZiNnLbeSGvajDt2nrp20Dyh6ZlhvHQeOkJN7iYGTYZmhsOLXMh5bY017N8Is20mYb7UGSEihkoELBD7FozBZ4btO7orjSVVXbmtm9swW6zgXu4MpbxBUztsdeL2jFOE4W8vF1tdgzPUxdT4=
  app: dikaeinstein-book-a-meal
  on:
    repo: Dikaeinstein/book-a-meal
    branch: develop
