export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_ERROR = 'FETCH_MENU_ERROR';
export const SETUP_MENU_SUCCESS = 'SETUP_MENU_SUCCESS';
export const SETUP_MENU_REQUEST = 'SETUP_MENU_REQUEST';
export const SETUP_MENU_ERROR = 'SETUP_MENU_ERROR';
