const meals = [
  {
    name: 'Spaghetti with meat balls',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 2,
  },
  {
    name: 'Efo riro and cow head',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 2,
  },
  {
    name: 'Bread and beans',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 2,
  },
  {
    name: 'Yam and egg',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 2,
  },
  {
    name: 'Akpo and vegetable soup',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
  {
    name: 'Nigeria jollof rice',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
  {
    name: 'Ghanian jollof rice',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
  {
    name: 'Moimoi and pap',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
  {
    name: 'Hot dog and hot chocolate',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
  {
    name: 'Yam and fish sauce',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
  {
    name: 'Jabalaya rice and Chicken',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
  {
    name: 'Yam porridge',
    description: 'Some dummy description',
    imageUrl: 'https://mydummyimgurl.com',
    price: '2000',
    userId: 1,
  },
];

export default meals;
