const initialState = {
  urls: [
    {
      id: 1,
      name: 'Sign In',
      link: 'signin',
    },
    {
      id: 2,
      name: 'Sign Up',
      link: 'signup',
    },
  ],
  menu: {
    isFetching: false,
    byId: {},
    menuId: 0,
    isSet: false,
    isSaving: false,
    fetchError: null,
    saveError: null,
    updateError: null,
    isUpdating: false,
  },
  user: {
    isSubmitting: false,
    loggedIn: false,
    data: {
      id: null,
      name: '',
      email: '',
      role: '',
    },
    error: null,
  },
  orders: {
    isFetching: false,
    isSaving: false,
    isUpdating: false,
    byId: {},
    allIds: [],
    checkedOutOrder: {},
    fetchError: null,
    saveError: null,
    updateError: null,
  },
  meals: {
    isFetching: false,
    isUpdating: false,
    isSaving: false,
    isDeleting: false,
    byId: {},
    allIds: [],
    fetchError: null,
    saveError: null,
    updateError: null,
    deleteError: null,
  },
  dashboard: {
    isFetchingTotalOrders: false,
    isFetchingTotalAmount: false,
    isUpdating: false,
    fetchTotalOrdersError: null,
    fetchTotalAmountError: null,
    isFetchingAllOrders: false,
    fetchAllOrdersError: null,
    updateOrderError: null,
    totalAmount: 0,
    totalOrders: 0,
    byId: {},
    allIds: [],
  },
};

export default initialState;
